"""Sample opportunities for local development (parity with ui/src/data/loader.ts)."""

from db_client.types import FieldValue, PropertyOpportunity, Source

SAMPLE_OPPORTUNITIES: list[PropertyOpportunity] = [
    PropertyOpportunity(
        id='sample-viable-property',
        address='456 Investment Ave, Tampa, FL 33606',
        location='Tampa, FL',
        listing_url='https://example.com/listing/456',
        purchase_price=FieldValue(
            value=180000,
            status='VERIFIED',
            confidence='HIGH',
            source='https://example.com/listing/456',
            evidence='Listing price $180,000',
        ),
        monthly_rent=FieldValue(
            value=2100,
            status='VERIFIED',
            confidence='HIGH',
            source='Lease agreement',
            evidence='Current tenant paying $2,100/month',
        ),
        annual_gross_rent=25200,
        annual_operating_expenses=6800,
        noi=18400,
        cap_rate=0.1022,
        hoa=FieldValue(
            value=250,
            status='VERIFIED',
            confidence='HIGH',
            source='HOA docs',
            evidence='HOA fee $250/month',
        ),
        assessment=FieldValue(
            value=0,
            status='VERIFIED',
            confidence='HIGH',
            source='HOA disclosure',
            evidence='No special assessments',
        ),
        confidence='HIGH',
        status='VIABLE',
        sources=[Source(label='Listing', url='https://example.com/listing/456')],
        ranked_at='2026-08-09T12:00:00Z',
    ),
    PropertyOpportunity(
        id='sample-watchlist-property',
        address='789 Pending St, Orlando, FL 32801',
        location='Orlando, FL',
        listing_url='https://example.com/listing/789',
        purchase_price=FieldValue(
            value=220000,
            status='VERIFIED',
            confidence='HIGH',
            source='https://example.com/listing/789',
            evidence='Listing price $220,000',
        ),
        monthly_rent=FieldValue(
            value=2400,
            status='ESTIMATED',
            confidence='MEDIUM',
            source='Rent comps',
            evidence='Based on nearby comparable properties',
            range_low=2200,
            range_high=2600,
        ),
        annual_gross_rent=28800,
        annual_operating_expenses=6500,
        noi=22300,
        cap_rate=0.1014,
        hoa=FieldValue(
            value=180,
            status='VERIFIED',
            confidence='HIGH',
            source='HOA docs',
            evidence='HOA fee $180/month',
        ),
        assessment=FieldValue(
            value=None,
            status='UNKNOWN',
            confidence='LOW',
            source='HOA disclosure pending',
            evidence='Assessment status unknown - awaiting HOA disclosure',
        ),
        confidence='MEDIUM',
        status='WATCHLIST',
        sources=[Source(label='Listing', url='https://example.com/listing/789')],
        ranked_at='2026-08-09T14:00:00Z',
    ),
    PropertyOpportunity(
        id='sample-rejected-property',
        address='123 Example St, Tampa, FL 33602',
        location='Tampa, FL',
        listing_url='https://example.com/listing/123',
        purchase_price=FieldValue(
            value=200000,
            status='VERIFIED',
            confidence='HIGH',
            source='https://example.com/listing/123',
            evidence='Listing asking price $200,000',
        ),
        monthly_rent=FieldValue(
            value=2200,
            status='ESTIMATED',
            confidence='MEDIUM',
            source='Rent comps',
            evidence='Comp A: $2,100/mo similar 2BR condo. Comp B: $2,300/mo same building.',
            range_low=2100,
            range_high=2300,
        ),
        annual_gross_rent=26400,
        annual_operating_expenses=12572,
        noi=13828,
        cap_rate=0.0691,
        hoa=FieldValue(
            value=485,
            status='VERIFIED',
            confidence='HIGH',
            source='https://example.com/listing/123',
            evidence='Listing states HOA $485/month',
        ),
        assessment=FieldValue(
            value=0,
            status='VERIFIED',
            confidence='HIGH',
            source='HOA disclosure document',
            evidence='HOA disclosure dated 2026-01 states no special assessments',
        ),
        confidence='MEDIUM',
        status='REJECTED',
        sources=[Source(label='Listing', url='https://example.com/listing/123')],
        ranked_at='2026-08-09T18:00:00Z',
    ),
]
