#!/usr/bin/env python3
"""Generate scout meta.json artifacts for Manta EC market screening."""

import json
import os
from datetime import datetime, timedelta, timezone

NOW = datetime(2026, 8, 10, 5, 0, 0, tzinfo=timezone.utc)
RESCREEN = NOW + timedelta(days=30)
TS = NOW.isoformat().replace("+00:00", "Z")
RESCREEN_TS = RESCREEN.isoformat().replace("+00:00", "Z")

# FazWaz Manta rental medians (Mar 2025): 1BR $419, 2BR $732, 3BR $825
# Scout applies STR premium (+15-25%) only when listing explicitly markets Airbnb/investment.

LISTINGS = [
    # --- RESEARCH (gross yield >= 10%) ---
    {
        "id": "orongo-unit-21-barbasquillo-manta-ec",
        "address": "Orongo Unit 21, Barbasquillo, Manta, Manabí, Ecuador",
        "building_name": "Orongo",
        "unit": "21",
        "property_type": "condo",
        "beds": 1,
        "baths": 1,
        "asking_price": 42223,
        "rough_monthly_rent": 450,
        "advertised_hoa": None,
        "listing_url": "https://trivo.com.ec/propiedades/orongo/",
        "decision": "RESEARCH",
        "notes": "Pre-sale studio 35.51m², delivery H2 2026. FazWaz 1BR Manta median $419; +7% for new Barbasquillo product → $450/mo gross yield 12.8%. Parking sold separately. Sibling units 10–33 in same building.",
        "rent_source": "FazWaz Manta 1BR median $419/mo, adjusted for new construction",
    },
    {
        "id": "orongo-unit-11-barbasquillo-manta-ec",
        "address": "Orongo Unit 11, Barbasquillo, Manta, Manabí, Ecuador",
        "building_name": "Orongo",
        "unit": "11",
        "property_type": "condo",
        "beds": 1,
        "baths": 1,
        "asking_price": 43046,
        "rough_monthly_rent": 450,
        "advertised_hoa": None,
        "listing_url": "https://trivo.com.ec/propiedades/orongo/",
        "decision": "RESEARCH",
        "notes": "Pre-sale studio 38.5m² piso 1, delivery H2 2026. Same yield math as unit 21; building cluster opportunity.",
        "rent_source": "FazWaz Manta 1BR median $419/mo, adjusted",
    },
    {
        "id": "orongo-unit-10-barbasquillo-manta-ec",
        "address": "Orongo Unit 10, Barbasquillo, Manta, Manabí, Ecuador",
        "building_name": "Orongo",
        "unit": "10",
        "property_type": "condo",
        "beds": 1,
        "baths": 1,
        "asking_price": 49912,
        "rough_monthly_rent": 450,
        "advertised_hoa": None,
        "listing_url": "https://trivo.com.ec/propiedades/orongo/",
        "decision": "RESEARCH",
        "notes": "Pre-sale studio 44.39m² piso 1. Gross yield 10.8% at $450/mo LTR estimate.",
        "rent_source": "FazWaz Manta 1BR median $419/mo, adjusted",
    },
    {
        "id": "nahla-unit-d-107-barbasquillo-manta-ec",
        "address": "Nahla Unit D-107, Barbasquillo, Manta, Manabí, Ecuador",
        "building_name": "Nahla",
        "unit": "D-107",
        "property_type": "condo",
        "beds": 1,
        "baths": 1,
        "asking_price": 58671,
        "rough_monthly_rent": 500,
        "advertised_hoa": None,
        "listing_url": "https://trivo.com.ec/propiedades/nahla/",
        "decision": "RESEARCH",
        "notes": "Immediate delivery; Airbnb-friendly per developer. Studio 40.98m². STR estimate $500/mo vs $419 LTR median → 10.2% gross. Full-amenity building (pool, gym, coworking).",
        "rent_source": "FazWaz 1BR median + STR premium; listing markets vacation rental",
    },
    {
        "id": "nahla-unit-d-105-barbasquillo-manta-ec",
        "address": "Nahla Unit D-105, Barbasquillo, Manta, Manabí, Ecuador",
        "building_name": "Nahla",
        "unit": "D-105",
        "property_type": "condo",
        "beds": 1,
        "baths": 1,
        "asking_price": 59444,
        "rough_monthly_rent": 500,
        "advertised_hoa": None,
        "listing_url": "https://trivo.com.ec/propiedades/nahla/",
        "decision": "RESEARCH",
        "notes": "Nahla studio 41.52m², immediate delivery, Airbnb-friendly. Gross yield 10.1% at $500/mo STR estimate.",
        "rent_source": "FazWaz 1BR median + STR premium",
    },
    {
        "id": "fez-manta-unit-209-barbasquillo-manta-ec",
        "address": "Fez Manta Unit 209, Barbasquillo, Manta, Manabí, Ecuador",
        "building_name": "Fez Manta",
        "unit": "209",
        "property_type": "condo",
        "beds": 1,
        "baths": 1,
        "asking_price": 62150,
        "rough_monthly_rent": 520,
        "advertised_hoa": None,
        "listing_url": "https://trivo.com.ec/propiedades/fez-manta/",
        "decision": "RESEARCH",
        "notes": "Pre-sale suite 32.29m² piso 2, delivery H2 2026, includes parking. $520/mo estimate → 10.0% gross yield borderline pass.",
        "rent_source": "FazWaz 1BR median $419 + amenity premium",
    },
    {
        "id": "nahla-unit-60-barbasquillo-manta-ec",
        "address": "Nahla Unit 60, Barbasquillo, Manta, Manabí, Ecuador",
        "building_name": "Nahla",
        "unit": "60",
        "property_type": "condo",
        "beds": 3,
        "baths": 2,
        "asking_price": 96900,
        "rough_monthly_rent": 825,
        "advertised_hoa": None,
        "listing_url": "https://trivo.com.ec/propiedades/nahla/",
        "decision": "RESEARCH",
        "notes": "3BR 107m² at Nahla; FazWaz 3BR Manta median $825/mo → 10.2% gross. Immediate delivery, Airbnb-friendly building.",
        "rent_source": "FazWaz Manta 3BR median $825/mo",
    },
    {
        "id": "poseidon-unit-12f-barbasquillo-manta-ec",
        "address": "Poseidon Building Unit 12F, Barbasquillo, Manta, Manabí, Ecuador",
        "building_name": "Poseidon",
        "unit": "12F",
        "property_type": "condo",
        "beds": 1,
        "baths": 1,
        "asking_price": 139000,
        "rough_monthly_rent": 1200,
        "advertised_hoa": 185,
        "listing_url": "https://ecuador.propertyshelf.com/en/front-page/rs1800320",
        "decision": "RESEARCH",
        "notes": "1/1 corner unit; listing cites 'most popular rental unit' in building. STR estimate $1,200/mo (El Murciélago oceanfront 2BR rents $1,200/mo per MLS rl2600064). Gross 10.4%; adjusted (1200-185)*12/139000 = 8.8% — passes gross screen, HOA flagged.",
        "rent_source": "Comparable Poseidon/oceanfront STR; listing rental popularity claim",
    },
    {
        "id": "torre-del-sol-barbasquillo-manta-ec",
        "address": "Torre del Sol, Ciudadela Universitaria, Barbasquillo, Manta, Manabí, Ecuador",
        "building_name": "Torre del Sol",
        "property_type": "condo",
        "beds": 2,
        "baths": 2,
        "asking_price": 139000,
        "rough_monthly_rent": 1200,
        "advertised_hoa": None,
        "listing_url": "https://manta360realty.com/departamento-venta-sur-de-manta-manta/9705059",
        "decision": "RESEARCH",
        "notes": "2/2 furnished 90m²; listing explicitly targets Airbnb year-round. STR $1,200/mo estimate (oceanfront 2BR comp) → 10.4% gross. Beach-access condo building; scan sibling units if available.",
        "rent_source": "MLS oceanfront 2BR rent comp $1,200/mo; listing Airbnb marketing",
    },
    {
        "id": "suite-vista-mar-centro-manta-ec",
        "address": "Suite vista al Mar, Malecón, Centro-Manta, Manabí, Ecuador",
        "property_type": "condo",
        "beds": 1,
        "baths": 1,
        "asking_price": 130000,
        "rough_monthly_rent": 1100,
        "advertised_hoa": None,
        "listing_url": "https://www.realtor.com/international/ec/manta-manabi-province/",
        "decision": "RESEARCH",
        "notes": "Oceanfront 1BR suite Centro-Manta per Realtor.com intl. STR $1,100/mo estimate → 10.15% gross. Verify HOA and exact unit on research pass.",
        "rent_source": "Oceanfront 1BR STR comp; Realtor.com listing $130,000",
    },
    # --- ARCHIVED REJECTS ---
    {
        "id": "torremarina-unit-3f-el-murciélago-manta-ec",
        "address": "TorreMarina Unit 3F, El Murciélago, Manta, Manabí, Ecuador",
        "building_name": "TorreMarina",
        "unit": "3F",
        "property_type": "condo",
        "beds": 2,
        "baths": 2,
        "asking_price": 117000,
        "rough_monthly_rent": 732,
        "advertised_hoa": 120,
        "listing_url": "https://mls-ecuador.com/en/real-estate/manta-real-estate/rs2600214",
        "decision": "REJECT",
        "notes": "Gross yield 7.5% at FazWaz 2BR median $732/mo. Adjusted (732-120)*12/117000 = 6.3%. Well-managed building but price/rent gap too wide for 10% cap path.",
        "rent_source": "FazWaz Manta 2BR median $732/mo",
    },
    {
        "id": "torre-marina-1br-el-murciélago-manta-ec",
        "address": "Torre Marina 1BR, El Murciélago, Manta, Manabí, Ecuador",
        "building_name": "Torre Marina",
        "property_type": "condo",
        "beds": 1,
        "baths": 1,
        "asking_price": 68000,
        "rough_monthly_rent": 500,
        "advertised_hoa": None,
        "listing_url": "https://www.owninecuador.com/forsale/torre-marina-1",
        "decision": "REJECT",
        "notes": "1BR 72m² steps from beach at $68K. $500/mo generous LTR estimate → 8.8% gross, below 10% threshold.",
        "rent_source": "FazWaz 1BR median $419 + location premium estimate",
    },
    {
        "id": "poseidon-unit-7f-barbasquillo-manta-ec",
        "address": "Poseidon Building Unit 7F, Barbasquillo, Manta, Manabí, Ecuador",
        "building_name": "Poseidon",
        "unit": "7F",
        "property_type": "condo",
        "beds": 2,
        "baths": 2,
        "asking_price": 199000,
        "rough_monthly_rent": 1300,
        "advertised_hoa": 369,
        "listing_url": "https://mls-ecuador.com/en/real-estate/manta-real-estate/rs2600215",
        "decision": "REJECT",
        "notes": "Verified rent $1,300/mo but gross yield only 7.8%. HOA $369/mo crushes adjusted yield to 5.6%. High HOA scrutiny flag.",
        "rent_source": "Listing stated current rent $1,300/mo",
    },
    {
        "id": "ibiza-unit-4f-umiña-manta-ec",
        "address": "Ibiza Building Unit 4F, Umiña, Manta, Manabí, Ecuador",
        "building_name": "Ibiza",
        "unit": "4F",
        "property_type": "condo",
        "beds": 2,
        "baths": 2,
        "asking_price": 239900,
        "rough_monthly_rent": 1200,
        "advertised_hoa": 252,
        "listing_url": "https://mls-ecuador.com/en/real-estate/manta-real-estate/rs2600324",
        "decision": "REJECT",
        "notes": "Premium beachfront 2/2; STR estimate $1,200/mo → 6.0% gross. Adjusted yield 4.7% with HOA. Luxury building — wrong price point for yield target.",
        "rent_source": "Oceanfront 2BR STR comp $1,200/mo",
    },
    {
        "id": "ibiza-unit-5f-umiña-manta-ec",
        "address": "Ibiza Building 5th Floor, Umiña, Manta, Manabí, Ecuador",
        "building_name": "Ibiza",
        "property_type": "condo",
        "beds": 3,
        "baths": 2,
        "asking_price": 259900,
        "rough_monthly_rent": 1000,
        "advertised_hoa": None,
        "listing_url": "https://www.realtor.com/international/ec/manta-manabi-province/",
        "decision": "REJECT",
        "notes": "3BR turn-key oceanview Ibiza at $259,900. Even $1,000/mo STR → 4.6% gross.",
        "rent_source": "Premium STR estimate",
    },
    {
        "id": "ibiza-unit-3br-furnished-umiña-manta-ec",
        "address": "Ibiza Building 3BR Furnished, Umiña, Manta, Manabí, Ecuador",
        "building_name": "Ibiza",
        "property_type": "condo",
        "beds": 3,
        "baths": 2,
        "asking_price": 275000,
        "rough_monthly_rent": 900,
        "advertised_hoa": None,
        "listing_url": "https://www.realtor.com/international/ec/manta-manabi-province/p3/",
        "decision": "REJECT",
        "notes": "3/2.5 furnished Ibiza beachfront. $900/mo STR → 3.9% gross.",
        "rent_source": "3BR STR estimate",
    },
    {
        "id": "arrecife-unit-5f-umiña-manta-ec",
        "address": "Arrecife Building 5F, Umiña, Manta, Manabí, Ecuador",
        "building_name": "Arrecife",
        "unit": "5F",
        "property_type": "condo",
        "beds": 3,
        "baths": 3,
        "asking_price": 198000,
        "rough_monthly_rent": 825,
        "advertised_hoa": 195,
        "listing_url": "https://mls.mls-ecuador.com/agencies/santosazuainversionesec/listings/rs2500678",
        "decision": "REJECT",
        "notes": "3/3 ocean-view 145m². FazWaz 3BR median $825 → 5.0% gross. Adjusted 3.8% with HOA $195.",
        "rent_source": "FazWaz 3BR median $825/mo",
    },
    {
        "id": "el-faro-unit-2f-ciudad-del-mar-manta-ec",
        "address": "El Faro Unit 2F, Ciudad del Mar, Manta, Manabí, Ecuador",
        "building_name": "El Faro",
        "unit": "2F",
        "property_type": "condo",
        "beds": 2,
        "baths": 2,
        "asking_price": 178000,
        "rough_monthly_rent": 732,
        "advertised_hoa": 40,
        "listing_url": "https://mls.mls-ecuador.com/agencies/ecuadoriancoastalproperties/listings/rs2401126",
        "decision": "REJECT",
        "notes": "Low HOA $40 but 2BR at $178K → 4.9% gross at median rent. Ciudad del Mar premium pricing.",
        "rent_source": "FazWaz 2BR median $732/mo",
    },
    {
        "id": "ciudad-del-mar-2br-oceanfront-manta-ec",
        "address": "Ciudad del Mar 2BR Oceanfront, Manta, Manabí, Ecuador",
        "building_name": "Ciudad del Mar",
        "property_type": "condo",
        "beds": 2,
        "baths": 2,
        "asking_price": 189900,
        "rough_monthly_rent": 800,
        "advertised_hoa": None,
        "listing_url": "https://www.realtor.com/international/ec/manta-manabi-province/p2/",
        "decision": "REJECT",
        "notes": "Oceanfront 2/2 with upgrades. $800/mo → 5.1% gross.",
        "rent_source": "2BR STR/LTR blend estimate",
    },
    {
        "id": "ciudad-del-mar-3br-condo-manta-ec",
        "address": "Ciudad del Mar 3BR Condominium, Manta, Manabí, Ecuador",
        "building_name": "Ciudad del Mar",
        "property_type": "condo",
        "beds": 3,
        "baths": 2,
        "asking_price": 183000,
        "rough_monthly_rent": 825,
        "advertised_hoa": None,
        "listing_url": "https://www.realtor.com/international/ec/manta-manabi-province/p3/",
        "decision": "REJECT",
        "notes": "3BR with balcony Ciudad del Mar. Median rent → 5.4% gross.",
        "rent_source": "FazWaz 3BR median",
    },
    {
        "id": "riva-di-mare-1br-flavio-reyes-manta-ec",
        "address": "Riva Di Mare 1BR, Av. Flavio Reyes, Manta, Manabí, Ecuador",
        "building_name": "Riva Di Mare",
        "property_type": "condo",
        "beds": 1,
        "baths": 1,
        "asking_price": 179700,
        "rough_monthly_rent": 950,
        "advertised_hoa": 150,
        "listing_url": "https://www.ecuadorshoresrealty.com/property/stunning-ocean-view-condo-perfect-for-vacationers-residents-or-investors-manta-ecuador/",
        "decision": "REJECT",
        "notes": "Tenant in place but rent undisclosed. Even $950/mo STR → 6.3% gross. Adjusted 5.3% with HOA.",
        "rent_source": "Optimistic STR estimate; tenant rent unknown",
    },
    {
        "id": "riva-di-mare-2br-flavio-reyes-manta-ec",
        "address": "Riva Di Mare 2BR, Edificio Riva de Mare, Manta, Manabí, Ecuador",
        "building_name": "Riva Di Mare",
        "property_type": "condo",
        "beds": 2,
        "baths": 2,
        "asking_price": 259990,
        "rough_monthly_rent": 900,
        "advertised_hoa": None,
        "listing_url": "https://www.realtor.com/international/ec/manta-manabi-province/p2/",
        "decision": "REJECT",
        "notes": "2BR Riva de Mare near coast. $900/mo → 4.2% gross.",
        "rent_source": "2BR STR estimate",
    },
    {
        "id": "barbasquillo-3br-apt-manta-ec",
        "address": "Barbasquillo 3BR Apartment, Manta, Manabí, Ecuador",
        "property_type": "condo",
        "beds": 3,
        "baths": 2,
        "asking_price": 340000,
        "rough_monthly_rent": 900,
        "advertised_hoa": None,
        "listing_url": "https://mls-ecuador.com/en/real-estate/manta-real-estate/rs2600320",
        "decision": "REJECT",
        "notes": "3/2 near coast with pool amenities. $900/mo generous → 3.2% gross.",
        "rent_source": "3BR premium rent estimate",
    },
    {
        "id": "grand-bay-3br-corner-manta-ec",
        "address": "Grand Bay 3BR Corner Unit, Manta, Manabí, Ecuador",
        "building_name": "Grand Bay",
        "property_type": "condo",
        "beds": 3,
        "baths": 2,
        "asking_price": 494800,
        "rough_monthly_rent": 1500,
        "advertised_hoa": None,
        "listing_url": "https://www.realtor.com/international/ec/manta-manabi-province/p2/",
        "decision": "REJECT",
        "notes": "Beachfront 3BR corner. Even $1,500/mo STR → 3.6% gross.",
        "rent_source": "Luxury STR estimate",
    },
    {
        "id": "oceania-sky-loft-manta-ec",
        "address": "Oceania Sky Loft 180, Edificio Oceania, Manta, Manabí, Ecuador",
        "building_name": "Oceania",
        "property_type": "condo",
        "beds": 1,
        "baths": 1,
        "asking_price": 194000,
        "rough_monthly_rent": 1500,
        "advertised_hoa": None,
        "listing_url": "https://www.realtor.com/international/ec/manta-manabi-province/p2/",
        "decision": "REJECT",
        "notes": "Ultra-luxury oceanfront loft. $1,500/mo STR → 9.3% gross — close but below 10%. Premium asset, not yield play.",
        "rent_source": "Luxury STR estimate",
    },
    {
        "id": "oceania-4br-beachfront-manta-ec",
        "address": "Oceania 4BR Beachfront, Manta, Manabí, Ecuador",
        "building_name": "Oceania",
        "property_type": "condo",
        "beds": 4,
        "baths": 4,
        "asking_price": 525000,
        "rough_monthly_rent": 2000,
        "advertised_hoa": None,
        "listing_url": "https://www.realtor.com/international/ec/manta-manabi-province/p2/",
        "decision": "REJECT",
        "notes": "4/4.5 Oceania luxury furnished. $2,000/mo → 4.6% gross.",
        "rent_source": "Luxury STR estimate",
    },
    {
        "id": "poseidon-9f-2br-barbasquillo-manta-ec",
        "address": "Poseidon Hotel Apt 9F, Barbasquillo, Manta, Manabí, Ecuador",
        "building_name": "Poseidon",
        "unit": "9F",
        "property_type": "condo",
        "beds": 2,
        "baths": 2,
        "asking_price": 230000,
        "rough_monthly_rent": 1300,
        "advertised_hoa": None,
        "listing_url": "https://www.realtor.com/international/ec/manta-manabi-province/p3/",
        "decision": "REJECT",
        "notes": "Poseidon 2BR full ocean views 9th floor. Using sibling verified rent $1,300 → 6.8% gross.",
        "rent_source": "Poseidon rs2600215 verified rent comp",
    },
    {
        "id": "poseidon-2br-under-190k-manta-ec",
        "address": "Poseidon 2BR Furnished, Barbasquillo, Manta, Manabí, Ecuador",
        "building_name": "Poseidon",
        "property_type": "condo",
        "beds": 2,
        "baths": 2,
        "asking_price": 189000,
        "rough_monthly_rent": 1300,
        "advertised_hoa": None,
        "listing_url": "https://www.fazwaz.com.ec/en/projects/ecuador/manabi/manta/manta/furnished-22-beachfront-prime-location-under-190k",
        "decision": "REJECT",
        "notes": "Poseidon 2/2 under $190K per FazWaz. $1,300 rent → 8.3% gross, below threshold.",
        "rent_source": "Poseidon verified rent comp",
    },
    {
        "id": "skyline-1br-presale-manta-ec",
        "address": "Skyline Manta 1BR Suite Presale, Manta, Manabí, Ecuador",
        "building_name": "Skyline Manta",
        "property_type": "condo",
        "beds": 1,
        "baths": 1,
        "asking_price": 155000,
        "rough_monthly_rent": 600,
        "advertised_hoa": None,
        "listing_url": "https://www.realtor.com/international/ec/manta-manabi-province/p2/",
        "decision": "REJECT",
        "notes": "Presale 1BR near La Quadra. $600/mo → 4.6% gross.",
        "rent_source": "1BR new construction estimate",
    },
    {
        "id": "torre-elit-1br-ciudad-del-mar-manta-ec",
        "address": "Torre Elit 1BR Suite, Ciudad del Mar, Manta, Manabí, Ecuador",
        "building_name": "Torre Elit",
        "property_type": "condo",
        "beds": 1,
        "baths": 1,
        "asking_price": 144900,
        "rough_monthly_rent": 700,
        "advertised_hoa": None,
        "listing_url": "https://www.realtor.com/international/ec/manta-manabi-province/p2/",
        "decision": "REJECT",
        "notes": "Oceanfront Elit suite presale. $700/mo → 5.8% gross.",
        "rent_source": "Oceanfront 1BR estimate",
    },
    {
        "id": "elite-towers-3br-oceanfront-manta-ec",
        "address": "Elite Towers 3BR, Manta, Manabí, Ecuador",
        "building_name": "Elite Towers",
        "property_type": "condo",
        "beds": 3,
        "baths": 2,
        "asking_price": 319900,
        "rough_monthly_rent": 1500,
        "advertised_hoa": 225,
        "listing_url": "https://www.ecuadorshoresrealty.com/property/3-2-double-balcony-fully-furnished-oceanfront-condo-manta-ecuador/",
        "decision": "REJECT",
        "notes": "Premium 3/2 oceanfront Elite Towers. Listing claims >$4K STR but at $1,500 conservative → 5.6% gross.",
        "rent_source": "Listing STR marketing; conservative $1,500 applied",
    },
    {
        "id": "edificio-buzios-3br-manta-ec",
        "address": "Edificio Buzios 3BR, Manta, Manabí, Ecuador",
        "building_name": "Edificio Buzios",
        "property_type": "condo",
        "beds": 3,
        "baths": 2,
        "asking_price": 289000,
        "rough_monthly_rent": 900,
        "advertised_hoa": None,
        "listing_url": "https://www.realtor.com/international/ec/manta-manabi-province/p3/",
        "decision": "REJECT",
        "notes": "Fully furnished Buzios 3BR. $900/mo → 3.7% gross.",
        "rent_source": "3BR furnished estimate",
    },
    {
        "id": "buzios-3br-oceanfront-barbasquillo-manta-ec",
        "address": "Edificio Buzios 3BR Oceanfront, Barbasquillo, Manta, Manabí, Ecuador",
        "building_name": "Edificio Buzios",
        "property_type": "condo",
        "beds": 3,
        "baths": 2,
        "asking_price": 275000,
        "rough_monthly_rent": 900,
        "advertised_hoa": None,
        "listing_url": "https://www.realtor.com/international/ec/manta-manabi-province/p3/",
        "decision": "REJECT",
        "notes": "Oceanfront Buzios 3BR. $900/mo → 3.9% gross.",
        "rent_source": "3BR STR estimate",
    },
    {
        "id": "santa-marianita-3br-oceanfront-manta-ec",
        "address": "Punta Tortuga 3BR Oceanfront, Santa Marianita, Manta, Manabí, Ecuador",
        "property_type": "condo",
        "beds": 3,
        "baths": 3,
        "asking_price": 439000,
        "rough_monthly_rent": 1200,
        "advertised_hoa": None,
        "listing_url": "https://mls-ecuador.com/en/real-estate/manta-real-estate/rs2600197",
        "decision": "REJECT",
        "notes": "Santa Marianita oceanfront 3/3 with private pool. $1,200/mo → 3.3% gross.",
        "rent_source": "Vacation rental estimate",
    },
    {
        "id": "nahla-unit-d-203-barbasquillo-manta-ec",
        "address": "Nahla Unit D-203, Barbasquillo, Manta, Manabí, Ecuador",
        "building_name": "Nahla",
        "unit": "D-203",
        "property_type": "condo",
        "beds": 2,
        "baths": 2,
        "asking_price": 93949,
        "rough_monthly_rent": 732,
        "advertised_hoa": None,
        "listing_url": "https://trivo.com.ec/propiedades/nahla/",
        "decision": "REJECT",
        "notes": "Nahla 2BR 81m². FazWaz 2BR median $732 → 9.4% gross — borderline reject (below 10%). STR $800 still only 10.2%; LTR path insufficient.",
        "rent_source": "FazWaz 2BR median $732/mo",
    },
    {
        "id": "nahla-unit-d-204-barbasquillo-manta-ec",
        "address": "Nahla Unit D-204, Barbasquillo, Manta, Manabí, Ecuador",
        "building_name": "Nahla",
        "unit": "D-204",
        "property_type": "condo",
        "beds": 2,
        "baths": 2,
        "asking_price": 99382,
        "rough_monthly_rent": 750,
        "advertised_hoa": None,
        "listing_url": "https://trivo.com.ec/propiedades/nahla/",
        "decision": "REJECT",
        "notes": "Nahla 2BR 86m². $750/mo STR → 9.1% gross.",
        "rent_source": "2BR STR estimate",
    },
    {
        "id": "nahla-unit-d-106-barbasquillo-manta-ec",
        "address": "Nahla Unit D-106, Barbasquillo, Manta, Manabí, Ecuador",
        "building_name": "Nahla",
        "unit": "D-106",
        "property_type": "condo",
        "beds": 1,
        "baths": 1,
        "asking_price": 66717,
        "rough_monthly_rent": 450,
        "advertised_hoa": None,
        "listing_url": "https://trivo.com.ec/propiedades/nahla/",
        "decision": "REJECT",
        "notes": "Nahla studio 34.53m² at $66,717. $450/mo → 8.1% gross.",
        "rent_source": "1BR adjusted estimate",
    },
    {
        "id": "fez-manta-unit-405-barbasquillo-manta-ec",
        "address": "Fez Manta Unit 405, Barbasquillo, Manta, Manabí, Ecuador",
        "building_name": "Fez Manta",
        "unit": "405",
        "property_type": "condo",
        "beds": 1,
        "baths": 1,
        "asking_price": 70043,
        "rough_monthly_rent": 450,
        "advertised_hoa": None,
        "listing_url": "https://trivo.com.ec/propiedades/fez-manta/",
        "decision": "REJECT",
        "notes": "Fez suite piso 4 at $70,043. $450/mo → 7.7% gross.",
        "rent_source": "1BR median adjusted",
    },
    {
        "id": "fez-manta-unit-210-barbasquillo-manta-ec",
        "address": "Fez Manta Unit 210, Barbasquillo, Manta, Manabí, Ecuador",
        "building_name": "Fez Manta",
        "unit": "210",
        "property_type": "condo",
        "beds": 2,
        "baths": 2,
        "asking_price": 109324,
        "rough_monthly_rent": 732,
        "advertised_hoa": None,
        "listing_url": "https://trivo.com.ec/propiedades/fez-manta/",
        "decision": "REJECT",
        "notes": "Fez 2BR 59.74m² pre-sale. Median rent → 8.0% gross.",
        "rent_source": "FazWaz 2BR median",
    },
    {
        "id": "fez-manta-unit-408-barbasquillo-manta-ec",
        "address": "Fez Manta Unit 408, Barbasquillo, Manta, Manabí, Ecuador",
        "building_name": "Fez Manta",
        "unit": "408",
        "property_type": "condo",
        "beds": 2,
        "baths": 2,
        "asking_price": 211287,
        "rough_monthly_rent": 800,
        "advertised_hoa": None,
        "listing_url": "https://trivo.com.ec/propiedades/fez-manta/",
        "decision": "REJECT",
        "notes": "Fez 2BR 102m² at $211K. $800/mo → 4.5% gross.",
        "rent_source": "2BR premium estimate",
    },
    {
        "id": "orongo-unit-12-barbasquillo-manta-ec",
        "address": "Orongo Unit 12, Barbasquillo, Manta, Manabí, Ecuador",
        "building_name": "Orongo",
        "unit": "12",
        "property_type": "condo",
        "beds": 1,
        "baths": 1,
        "asking_price": 55503,
        "rough_monthly_rent": 450,
        "advertised_hoa": None,
        "listing_url": "https://trivo.com.ec/propiedades/orongo/",
        "decision": "REJECT",
        "notes": "Orongo studio 47.22m² at $55,503. $450/mo → 9.7% gross — just below 10% threshold.",
        "rent_source": "1BR adjusted estimate",
    },
    {
        "id": "orongo-unit-13-barbasquillo-manta-ec",
        "address": "Orongo Unit 13, Barbasquillo, Manta, Manabí, Ecuador",
        "building_name": "Orongo",
        "unit": "13",
        "property_type": "condo",
        "beds": 1,
        "baths": 1,
        "asking_price": 44167,
        "rough_monthly_rent": 450,
        "advertised_hoa": None,
        "listing_url": "https://trivo.com.ec/propiedades/orongo/",
        "decision": "RESEARCH",
        "notes": "Orongo studio 38.96m² piso 1 at $44,167. $450/mo → 12.2% gross. Sibling to unit 21.",
        "rent_source": "FazWaz 1BR median adjusted",
    },
    {
        "id": "dep-manta-2br-ocean-view-manta-ec",
        "address": "Dep-Manta 2BR Ocean View + Suite, Manta, Manabí, Ecuador",
        "property_type": "condo",
        "beds": 2,
        "baths": 2,
        "asking_price": 190000,
        "rough_monthly_rent": 900,
        "advertised_hoa": None,
        "listing_url": "https://www.realtor.com/international/ec/manta-manabi-province/p3/",
        "decision": "REJECT",
        "notes": "2BR + independent suite ocean view. $900/mo → 5.7% gross.",
        "rent_source": "Multi-unit rent estimate",
    },
    {
        "id": "departamento-vista-mar-2br-manta-ec",
        "address": "Departamento vista al mar 2BR, Manta, Manabí, Ecuador",
        "property_type": "condo",
        "beds": 2,
        "baths": 2,
        "asking_price": 170000,
        "rough_monthly_rent": 800,
        "advertised_hoa": None,
        "listing_url": "https://www.realtor.com/international/ec/manta-manabi-province/p3/",
        "decision": "REJECT",
        "notes": "Beachfront 2BR at $170K. $800/mo → 5.6% gross.",
        "rent_source": "2BR beachfront estimate",
    },
    {
        "id": "barbasquillo-2br-apt-230k-manta-ec",
        "address": "Barbasquillo 2BR Apartment, Manta, Manabí, Ecuador",
        "property_type": "condo",
        "beds": 2,
        "baths": 2,
        "asking_price": 230000,
        "rough_monthly_rent": 850,
        "advertised_hoa": None,
        "listing_url": "https://www.realtor.com/international/ec/manta-manabi-province/p3/",
        "decision": "REJECT",
        "notes": "Barbasquillo 2BR near coast. $850/mo → 4.4% gross.",
        "rent_source": "2BR estimate",
    },
    {
        "id": "lanzarote-unit-6b-el-murciélago-manta-ec",
        "address": "Lanzarote Unit 6B, El Murciélago, Manta, Manabí, Ecuador",
        "building_name": "Lanzarote",
        "unit": "6B",
        "property_type": "condo",
        "beds": 2,
        "baths": 2,
        "asking_price": 198440,
        "rough_monthly_rent": 1200,
        "advertised_hoa": 164,
        "listing_url": "https://mls-ecuador.com/en/agencies/ecuadorshoresrealty/ecuadorshoresrealty-investment/rs2300228",
        "decision": "REJECT",
        "notes": "New oceanfront Lanzarote 2/2 pre-construction. $1,200 STR → 7.3% gross. HOA $164.",
        "rent_source": "Oceanfront 2BR STR comp",
    },
    {
        "id": "3br-oceanfront-gem-manta-ec",
        "address": "3BR Oceanfront Gem, Manta, Manabí, Ecuador",
        "property_type": "condo",
        "beds": 3,
        "baths": 2,
        "asking_price": 264500,
        "rough_monthly_rent": 1000,
        "advertised_hoa": None,
        "listing_url": "https://www.realtor.com/international/ec/manta-manabi-province/p3/",
        "decision": "REJECT",
        "notes": "3BR oceanfront toes-in-sand. $1,000/mo → 4.5% gross.",
        "rent_source": "3BR STR estimate",
    },
    {
        "id": "skorpios-3br-beachfront-manta-ec",
        "address": "Skorpios Building 3BR Beachfront, Manta, Manabí, Ecuador",
        "building_name": "Skorpios",
        "property_type": "condo",
        "beds": 3,
        "baths": 2,
        "asking_price": 394000,
        "rough_monthly_rent": 1200,
        "advertised_hoa": None,
        "listing_url": "https://www.realtor.com/international/ec/manta-manabi-province/p3/",
        "decision": "REJECT",
        "notes": "Skorpios 3BR custom upgrades beachfront. $1,200/mo → 3.7% gross.",
        "rent_source": "Luxury STR estimate",
    },
    {
        "id": "ibiza-3br-barbasquillo-260k-manta-ec",
        "address": "Ibiza 3BR Near Coast, Barbasquillo, Manta, Manabí, Ecuador",
        "building_name": "Ibiza",
        "property_type": "condo",
        "beds": 3,
        "baths": 2,
        "asking_price": 260000,
        "rough_monthly_rent": 900,
        "advertised_hoa": None,
        "listing_url": "https://www.realtor.com/international/ec/manta-manabi-province/p2/",
        "decision": "REJECT",
        "notes": "Ibiza 3BR near coast/oceanfront. $900/mo → 4.2% gross.",
        "rent_source": "3BR STR estimate",
    },
    {
        "id": "oceanfront-penthouse-lease-ciudad-del-mar-manta-ec",
        "address": "Penthouse Ciudad del Mar Oceanfront (lease), Manta, Manabí, Ecuador",
        "building_name": "Ciudad del Mar",
        "property_type": "condo",
        "beds": 3,
        "baths": 3,
        "asking_price": 480000,
        "rough_monthly_rent": 2400,
        "advertised_hoa": None,
        "listing_url": "https://mls-ecuador.com/en/real-estate/manta-real-estate/rl2600080",
        "decision": "REJECT",
        "notes": "Lease-only listing ($2,400/mo); imputed value ~$480K at 6% cap for screening. Not a purchase candidate — comp for Ciudad del Mar penthouse rents.",
        "rent_source": "MLS lease listing rl2600080",
    },
]


def gross_yield(price: float, rent: float) -> float:
    return round((rent * 12) / price, 4)


def build_meta(entry: dict) -> dict:
    gy = gross_yield(entry["asking_price"], entry["rough_monthly_rent"])
    snapshot = {
        "price": entry["asking_price"],
        "rough_monthly_rent": entry["rough_monthly_rent"],
        "rough_gross_yield": gy,
        "advertised_hoa": entry.get("advertised_hoa"),
        "screened_at": TS,
    }
    base = {
        "id": entry["id"],
        "address": entry["address"],
        "location": "Manta, Manabí, Ecuador",
        "listing_url": entry["listing_url"],
        "market_id": "manta-ec",
        "created_at": TS,
        "updated_at": TS,
        "last_screened_at": TS,
        "screening_snapshot": snapshot,
        "scout_notes": entry["notes"],
        "property_type": entry.get("property_type"),
        "building_name": entry.get("building_name"),
        "unit": entry.get("unit"),
        "beds": entry.get("beds"),
        "baths": entry.get("baths"),
        "asking_price": entry["asking_price"],
        "rough_monthly_rent": entry["rough_monthly_rent"],
        "rough_gross_yield": gy,
        "advertised_hoa": entry.get("advertised_hoa"),
        "rent_source": entry.get("rent_source"),
        "rent_confidence": "MEDIUM",
    }
    if entry["decision"] == "RESEARCH":
        base.update(
            {
                "workflow_state": "SCREENED",
                "scout_decision": "RESEARCH",
            }
        )
    else:
        base.update(
            {
                "workflow_state": "ARCHIVED",
                "scout_decision": "REJECT",
                "archive_reason": "scout_reject",
                "rescreen_after": RESCREEN_TS,
                "rescreen_count": 0,
            }
        )
    return {k: v for k, v in base.items() if v is not None}


def main() -> None:
    root = os.path.join(os.path.dirname(__file__), "..", "data", "properties")
    research = 0
    reject = 0
    for entry in LISTINGS:
        meta = build_meta(entry)
        prop_dir = os.path.join(root, entry["id"])
        os.makedirs(prop_dir, exist_ok=True)
        path = os.path.join(prop_dir, "meta.json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(meta, f, indent=2)
            f.write("\n")
        if entry["decision"] == "RESEARCH":
            research += 1
        else:
            reject += 1
    print(f"Generated {len(LISTINGS)} meta.json files: {research} RESEARCH, {reject} REJECT")


if __name__ == "__main__":
    main()
